server:
  port : 8082
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: login-app
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEY_CLOAK_BASE_URL}/realms/SpringBootKeycloak
            user-name-attribute: preferred_username
      resourceserver:
        jwt.issuer-uri: ${KEY_CLOAK_BASE_URL}/realms/SpringBootKeycloak